networks:
  my_net:
volumes:
  my_db:

services:

  api:
    build: .
    container_name: banco-do-brasil-api
    ports:
      - "8080:8080"
    networks:
      - my_net
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.4.3-noble
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=bancodobrasil-api
      - TZ=America/Sao_Paulo
    networks:
      - my_net
    volumes:
      - "my_db:/var/lib/mysql"