# spring boot
spring.application.name = banco
spring.output.ansi.enabled = always
server.port = 8080

# database
spring.datasource.url = jdbc:mariadb://localhost:3306/banco_do_brasil?serverTimezone=America/Sao_Paulo
spring.datasource.username = root
spring.datasource.password = bancodobrasil-api
spring.datasource.driverClassName = org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.properties.hibernate.jdbc.time_zone = UTC
spring.jpa.defer-datasource-initialization = true
spring.sql.init.mode = ALWAYS
spring.sql.init.schema-locations = classpath:data*.sql