package br.com.bb.banco.entity.types;

public enum Ocupacao {
    DESEMPREGADO, ESTUDANTE, APOSENTADO, AUTONOMO, EMPRESARIO, AGRICULTOR, MEDICO,
    ENGENHEIRO, MILITAR, DESENVOLVEDOR_DE_SOFTWARE, ADVOGADO, ENFERMEIRO, DESIGNER,
    PSICOLOGO, ARQUITETO, VETERINARIO, JUIZ, PROFESSOR, PERSONAL_TRAINER, DENTISTA,
    FISIOTERAPEUTA, ECONOMISTA;

}
