package br.com.bb.banco.entity.types;

public enum TipoLinhaDeCredito {
    FINANCIAMENTO, FINANCIAMENTO_AGRO, FINANCIAMENTO_BENS_SERVICOS, 
    CDC, ANTECIPACAO, GARANTIA, RENOVACAO, PORTABILIDADE
}
