package br.com.bb.banco.entity.types;

public enum TipoLinhaDeCredito {
    
    ANTECIPAR_DECIMO_TERCEIRO, ANTECIPAR_IRPF, ANTECIPAR_FGTS,

    CREDITO_SALARIO, CREDITO_AUTOMATICO, CREDITO_BENEFICIO,  
    
    GARANTIA_IMOVEL, GARANTIA_VEICULO, GARANTIA_INVESTIMENTO,

    FINANCIAMENTO_CARRO, FINANCIAMENTO_MOTO, FINANCIAMENTO_IMOBILIARIO,

    CREDITO_MOBILIDADE, CREDITO_REALIZA, CREDITO_ENERGIA_RENOVAVEL, BENS_SERVICOS_PCD,

}
